spring:
  application:
    name: 10.SpringBootProject2
  datasource: 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: Tupa
    password: Kijhocche
    
